// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for About documents */
interface AboutDocumentData {
  /**
   * Title field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Prismic About Title
   * - **API ID Path**: about.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
  /**
   * Title2 field in *About*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Home Slice Model
   * - **API ID Path**: about.title2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title2: prismic.TitleField;
  /**
   * Text field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  text: prismic.GroupField<Simplify<AboutDocumentDataTextItem>>;
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Item in About → Text
 *
 */
export interface AboutDocumentDataTextItem {
  /**
   * Text1 field in *About → Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text[].text1
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text1: prismic.KeyTextField;
  /**
   * Text2 field in *About → Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text[].text2
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text2: prismic.KeyTextField;
}
/**
 * Slice for *About → Slice Zone*
 *
 */
type AboutDocumentDataSlicesSlice = HomeSliceSlice;
/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;
/** Content for contact documents */
interface ContactDocumentData {
  /**
   * formText field in *contact*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.formtext[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  formtext: prismic.GroupField<Simplify<ContactDocumentDataFormtextItem>>;
  /**
   * Slice Zone field in *contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Item in contact → formText
 *
 */
export interface ContactDocumentDataFormtextItem {
  /**
   * emailField field in *contact → formText*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.formtext[].emailfield
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  emailfield: prismic.KeyTextField;
  /**
   * nameField field in *contact → formText*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.formtext[].namefield
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  namefield: prismic.KeyTextField;
  /**
   * firstNameField field in *contact → formText*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.formtext[].firstnamefield
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  firstnamefield: prismic.KeyTextField;
  /**
   * messsageField field in *contact → formText*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.formtext[].messsagefield
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  messsagefield: prismic.KeyTextField;
}
/**
 * Slice for *contact → Slice Zone*
 *
 */
type ContactDocumentDataSlicesSlice = never;
/**
 * contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;
/** Content for Home documents */
interface HomeDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
  /**
   * Title2 field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title2: prismic.TitleField;
  /**
   * Pix field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.pix
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  pix: prismic.ImageField<never>;
  /**
   * Text field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.test[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  test: prismic.GroupField<Simplify<HomeDocumentDataTestItem>>;
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Item in Home → Text
 *
 */
export interface HomeDocumentDataTestItem {
  /**
   * Text1 field in *Home → Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.test[].text1
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text1: prismic.KeyTextField;
  /**
   * text2 field in *Home → Text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.test[].text2
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text2: prismic.KeyTextField;
}
/**
 * Slice for *Home → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice = HomeSliceSlice;
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for home_custom_type documents */
interface HomeCustomTypeDocumentData {
  /**
   * title field in *home_custom_type*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_custom_type.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * description field in *home_custom_type*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_custom_type.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Text field in *home_custom_type*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_custom_type.text[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  text: prismic.GroupField<Simplify<HomeCustomTypeDocumentDataTextItem>>;
}
/**
 * Item in home_custom_type → Text
 *
 */
export interface HomeCustomTypeDocumentDataTextItem {
  /**
   * text2 field in *home_custom_type → Text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_custom_type.text[].text2
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text2: prismic.RichTextField;
  /**
   * text3 field in *home_custom_type → Text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_custom_type.text[].text3
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text3: prismic.RichTextField;
}
/**
 * home_custom_type document from Prismic
 *
 * - **API ID**: `home_custom_type`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeCustomTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomeCustomTypeDocumentData>,
    "home_custom_type",
    Lang
  >;
/** Content for Navigation documents */
interface NavigationDocumentData {
  /**
   * Name field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismic.RichTextField;
  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = NavbarSlice;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;
/** Content for Services documents */
interface ServicesDocumentData {
  /**
   * card field in *Services*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  card: prismic.GroupField<Simplify<ServicesDocumentDataCardItem>>;
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Item in Services → card
 *
 */
export interface ServicesDocumentDataCardItem {
  /**
   * slug field in *Services → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.card[].slug
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  slug: prismic.KeyTextField;
  /**
   * cardname field in *Services → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.card[].cardname
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  cardname: prismic.KeyTextField;
  /**
   * cardimg field in *Services → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.card[].cardimg
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  cardimg: prismic.ImageField<never>;
  /**
   * carddescription field in *Services → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.card[].carddescription
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  carddescription: prismic.RichTextField;
}
/**
 * Slice for *Services → Slice Zone*
 *
 */
type ServicesDocumentDataSlicesSlice = never;
/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;
export type AllDocumentTypes =
  | AboutDocument
  | ContactDocument
  | HomeDocument
  | HomeCustomTypeDocument
  | NavigationDocument
  | ServicesDocument;
/**
 * Primary content in HomeSlice → Primary
 *
 */
interface HomeSliceSliceDefaultPrimary {
  /**
   * SliceTitle field in *HomeSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_slice.primary.slicetitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  slicetitle: prismic.KeyTextField;
  /**
   * SliceDescription field in *HomeSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_slice.primary.slicedescription
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  slicedescription: prismic.KeyTextField;
}
/**
 * Item in HomeSlice → Items
 *
 */
export interface HomeSliceSliceDefaultItem {
  /**
   * BlogImage field in *HomeSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_slice.items[].blogimage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  blogimage: prismic.ImageField<never>;
}
/**
 * Default variation for HomeSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeSliceSliceDefaultPrimary>,
  Simplify<HomeSliceSliceDefaultItem>
>;
/**
 * Slice variation for *HomeSlice*
 *
 */
type HomeSliceSliceVariation = HomeSliceSliceDefault;
/**
 * HomeSlice Shared Slice
 *
 * - **API ID**: `home_slice`
 * - **Description**: `HomeSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomeSliceSlice = prismic.SharedSlice<
  "home_slice",
  HomeSliceSliceVariation
>;
/**
 * Primary content in NavbarItem → Primary
 *
 */
interface NavbarSliceDefaultPrimary {
  /**
   * Name field in *NavbarItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismic.RichTextField;
  /**
   * Slug field in *NavbarItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.primary.slug
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  slug: prismic.KeyTextField;
}
/**
 * Item in NavbarItem → Items
 *
 */
export interface NavbarSliceDefaultItem {
  /**
   * Child Name field in *NavbarItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.items[].child_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  child_name: prismic.RichTextField;
  /**
   * Child Slug field in *NavbarItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.items[].slug
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  slug: prismic.KeyTextField;
}
/**
 * Default variation for NavbarItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavbarSliceDefaultPrimary>,
  Simplify<NavbarSliceDefaultItem>
>;
/**
 * Slice variation for *NavbarItem*
 *
 */
type NavbarSliceVariation = NavbarSliceDefault;
/**
 * NavbarItem Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: `Navbar`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarSlice = prismic.SharedSlice<"navbar", NavbarSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AboutDocumentData,
      AboutDocumentDataTextItem,
      AboutDocumentDataSlicesSlice,
      AboutDocument,
      ContactDocumentData,
      ContactDocumentDataFormtextItem,
      ContactDocumentDataSlicesSlice,
      ContactDocument,
      HomeDocumentData,
      HomeDocumentDataTestItem,
      HomeDocumentDataSlicesSlice,
      HomeDocument,
      HomeCustomTypeDocumentData,
      HomeCustomTypeDocumentDataTextItem,
      HomeCustomTypeDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      NavigationDocument,
      ServicesDocumentData,
      ServicesDocumentDataCardItem,
      ServicesDocumentDataSlicesSlice,
      ServicesDocument,
      AllDocumentTypes,
      HomeSliceSliceDefaultPrimary,
      HomeSliceSliceDefaultItem,
      HomeSliceSliceDefault,
      HomeSliceSliceVariation,
      HomeSliceSlice,
      NavbarSliceDefaultPrimary,
      NavbarSliceDefaultItem,
      NavbarSliceDefault,
      NavbarSliceVariation,
      NavbarSlice,
    };
  }
}
