// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  home_slice: dynamic(() => import("./HomeSlice")),
  navbar: dynamic(() => import("./NavbarItem")),
};
